name: Windows

on: [push]

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: configure
      run: |
        cmake -B build/debug   -D ZTD_OUT_PTR_TESTS=ON -D ZTD_OUT_PTR_EXAMPLES=ON
        cmake -B build/release -D ZTD_OUT_PTR_TESTS=ON -D ZTD_OUT_PTR_EXAMPLES=ON

    - name: build
      run: |
        cmake --build build/debug   --config Debug
        cmake --build build/release --config Release

    - name: test
      run: |
        cd build/debug
        ctest --build-config Debug
        cd ../..
        cd build/release
        ctest --build-config Release
        cd ../..
